spring:
  application:
    name: industry_iiot
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/machinery_db
    username: iiot_user
    password: 135790
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: iiot
    password: iiot